### ISSUE TITLE
medkits restore health to 120

### ISSUE THREAD

**Issue by Nephatrine** [q2vr/quake2vr#29]
nvm I'm totally wrong

**Comment by dghost** [comment]
Hm. That should occur with KMQuake 2 as well. Change is due to the integration of the lithium mod into the game library. The `max_health_dm` cvar controls this behavior.

A full list of the Lithium defaults can be found [here](https://github.com/mattayres/li2mod/blob/6415a7ecf5e823f14245b0f1742b2c1b14845117/lithium/lithium.cfg), with a stock version [here](https://github.com/mattayres/li2mod/blob/6415a7ecf5e823f14245b0f1742b2c1b14845117/lithium/stock.cfg). Not all the cvar's are the same though.

At some point I need to go through and restore the stock behavior.

**Comment by Nephatrine** [comment]
Yeah I realized that when I went to test kmq2, I just did map q2dm1 and didn't actually start a DM game. In DM it definitely does go up to 120 there too. And yeah there's a lot of extra stuff in kmq2's game library - though most of its perfectly fine.

**Comment by dghost** [comment]
Yeeeaaaaaah, unfortunately there is. KMQ2 is, for all purposes, kind of a bastardized collection of most of the major mods, with very little regard for stock Q2. Sometimes that's a good thing, sometimes it isn't. I've slowly been restoring stock Q2 behavior in places where it makes the most sense (i.e., restoring the Q2 railgun effect), but it's a long process and I haven't had much time to do anything recently.

A while back I tested switching over to the Yamagi Q2 libraries because they are essentially stock + bug fixes. If you want to fiddle with a purer game library they are the gold standard - you can either compile them with the updated game interface, or if you remove the #define Q2VR_ENGINE_MOD macro it *should* be able to build a version of the engine that loads stock game DLL's. It's been a bit since I tested it, though.

Ultimately I decided to stick with the existing ones because they have a lot of "nice" additions that really helps the VR single player experience. Still, there's a lot of room for improvement - which is part of why there hasn't been a recent "official" release.

**Comment by Nephatrine** [comment]
The the new kmq2 update has a lot of nice things like http download, decoupled network/video fps, and basegame/basegame2 support so I don't mind the choice of engine at all really. It is turning out to be a little bit more work than I thought though to get the relevant changes into q2vr because a lot of stuff has been shuffled around or replaced.

Btw for loading stock game dlls if that #define doesn't work, a really lame workaround that works is to launch an r1q2 (or whatever vanilla engine) dedicated server with whatever mod it is and then connect to it from kmquake2 client with the original q2 protocol.

**Comment by dghost** [comment]
Interesting. Do you have a link for the kmq2 update? I don't see it on the main website.

And yeah, I wound up changing a bunch.

**Comment by Nephatrine** [comment]
Binaries: www.markshan.com/knightmare/downloads/kmquake2_020_update7_test3.zip
Source code: www.markshan.com/knightmare/downloads/kmquake2_020_update7_test3_src.7z

kmquake2.txt in the source package has the full changelog

**Comment by dghost** [comment]
Thanks! I'm about a week away from having to defend my masters thesis so I don't quite have time at the moment, but when I get a chance I definitely am going to try to merge changes in.
